package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestEndToEnd(t *testing.T) {
	// Skip if protoc or protoc-gen-go aren't available.
	if _, err := exec.LookPath("protoc"); err != nil {
		t.Skip("protoc not found, skipping e2e test")
	}
	if _, err := exec.LookPath("protoc-gen-go"); err != nil {
		t.Skip("protoc-gen-go not found, skipping e2e test")
	}

	// Build the plugin binary.
	pluginBin := filepath.Join(t.TempDir(), "protoc-gen-extend")
	build := exec.Command("go", "build", "-o", pluginBin, ".")
	build.Dir = projectRoot(t)
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("failed to build plugin: %s\n%s", err, out)
	}

	tests := []struct {
		name        string
		proto       string
		sidecar     string
		sidecarRoot string // if set, place sidecar here instead of next to proto
		wantOutput  []string
		wantErr     string
	}{
		{
			name: "basic extensions",
			proto: `
syntax = "proto3";
package test;
option go_package = "example.com/testpb";

message User {
  string first_name = 1;
  string last_name = 2;
}
`,
			sidecar: `//go:build ignore

package testpb

func (m *User) FullName() string {
	return m.FirstName + " " + m.LastName
}
`,
			wantOutput: []string{
				"func (m *User) FullName() string",
				"package testpb",
				"Code generated by protoc-gen-extend",
			},
		},
		{
			name: "sidecar with imports",
			proto: `
syntax = "proto3";
package test;
option go_package = "example.com/testpb";

message User {
  string first_name = 1;
  string last_name = 2;
}
`,
			sidecar: `//go:build ignore

package testpb

import "strings"

func (m *User) FullName() string {
	return strings.TrimSpace(m.FirstName + " " + m.LastName)
}
`,
			wantOutput: []string{
				`"strings"`,
				"func (m *User) FullName() string",
			},
		},
		{
			name: "unknown receiver type",
			proto: `
syntax = "proto3";
package test;
option go_package = "example.com/testpb";

message User {
  string first_name = 1;
}
`,
			sidecar: `//go:build ignore

package testpb

func (m *Account) DoSomething() {}
`,
			wantErr: "Account is not a message",
		},
		{
			name: "error suggests available messages",
			proto: `
syntax = "proto3";
package test;
option go_package = "example.com/testpb";

message User {
  string first_name = 1;
}

message Team {
  string name = 1;
}
`,
			sidecar: `//go:build ignore

package testpb

func (m *Foo) Bad() {}
`,
			wantErr: "available messages: User, Team",
		},
		{
			name: "sidecar_root option",
			proto: `
syntax = "proto3";
package test;
option go_package = "example.com/testpb";

message Config {
  string key = 1;
  string value = 2;
}
`,
			sidecar: `//go:build ignore

package testpb

func (c *Config) IsEmpty() bool {
	return c.Key == "" && c.Value == ""
}
`,
			sidecarRoot: "extensions", // place sidecar in a separate dir
			wantOutput: []string{
				"func (c *Config) IsEmpty() bool",
			},
		},
		{
			name: "no sidecar file",
			proto: `
syntax = "proto3";
package test;
option go_package = "example.com/testpb";

message Empty {}
`,
			// no sidecar — plugin should produce no output and no error
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			protoDir := filepath.Join(tmpDir, "proto")
			outDir := filepath.Join(tmpDir, "gen")
			if err := os.MkdirAll(protoDir, 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				t.Fatal(err)
			}

			// Write proto file.
			protoFile := filepath.Join(protoDir, "test.proto")
			if err := os.WriteFile(protoFile, []byte(test.proto), 0o644); err != nil {
				t.Fatal(err)
			}

			// Write sidecar file.
			// Resolve the sidecar root directory. If the test specifies a
			// separate sidecarRoot, use that; otherwise default to placing
			// sidecars next to the proto files (which requires telling the
			// plugin where to look via sidecar_root, since protoc doesn't
			// expose --proto_path to plugins).
			var sidecarDir string
			if test.sidecarRoot != "" {
				sidecarDir = filepath.Join(tmpDir, test.sidecarRoot)
			} else {
				sidecarDir = protoDir
			}

			if test.sidecar != "" {
				if err := os.MkdirAll(sidecarDir, 0o755); err != nil {
					t.Fatal(err)
				}
				sidecarFile := filepath.Join(sidecarDir, "test.proto.ext.go")
				if err := os.WriteFile(sidecarFile, []byte(test.sidecar), 0o644); err != nil {
					t.Fatal(err)
				}
			}

			// Run protoc with our plugin. Always pass sidecar_root so the
			// plugin knows where to find sidecar files.
			extendOpt := "sidecar_root=" + sidecarDir + ",paths=source_relative"
			args := []string{
				"--proto_path=" + protoDir,
				"--plugin=protoc-gen-extend=" + pluginBin,
				"--extend_out=" + extendOpt + ":" + outDir,
			}
			args = append(args, protoFile)

			cmd := exec.Command("protoc", args...)
			out, err := cmd.CombinedOutput()

			if test.wantErr != "" {
				if err == nil {
					t.Fatalf("expected error containing %q, but protoc succeeded", test.wantErr)
				}
				if !strings.Contains(string(out), test.wantErr) {
					t.Fatalf("expected error containing %q, got:\n%s", test.wantErr, out)
				}
				return
			}

			if err != nil {
				t.Fatalf("protoc failed: %s\n%s", err, out)
			}

			// Check generated output.
			genFile := filepath.Join(outDir, "test_ext.pb.go")
			if len(test.wantOutput) == 0 {
				// Expect no output file.
				if _, err := os.Stat(genFile); err == nil {
					t.Fatal("expected no generated file, but one was created")
				}
				return
			}

			content, err := os.ReadFile(genFile)
			if err != nil {
				t.Fatalf("failed to read generated file: %s", err)
			}

			for _, want := range test.wantOutput {
				if !strings.Contains(string(content), want) {
					t.Errorf("generated file missing expected content %q\n\ngot:\n%s", want, content)
				}
			}
		})
	}
}

func projectRoot(t *testing.T) string {
	t.Helper()
	// We're running from the project root already in `go test`.
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return cwd
}
