package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateExtensions looks for sidecar .proto.ext.go files next to the proto file
// and emits them into the generated output with the correct package name.
func generateExtensions(gen *protogen.Plugin, file *protogen.File, sidecarRoot string) error {
	protoPath := file.Proto.GetName()
	protoDir := filepath.Dir(protoPath)

	// The sidecar file convention: <name>.proto.ext.go sits next to <name>.proto.
	baseName := strings.TrimSuffix(filepath.Base(protoPath), ".proto")
	sidecarName := baseName + ".proto.ext.go"

	// Search for the sidecar file. protoc doesn't give us the absolute path
	// to the proto file directly, so we search proto_path entries, the
	// sidecar_root option, and the current working directory.
	sidecarPath, err := findSidecar(protoDir, sidecarName, sidecarRoot)
	if err != nil {
		return err
	}
	if sidecarPath == "" {
		// No sidecar file found — nothing to do.
		return nil
	}

	// Build the set of known message names from the proto file.
	knownMessages := make(map[string]bool)
	var messageNames []string
	for _, msg := range file.Messages {
		knownMessages[msg.GoIdent.GoName] = true
		messageNames = append(messageNames, msg.GoIdent.GoName)
		addNestedMessages(knownMessages, msg)
	}

	content, err := parseSidecarFile(sidecarPath, knownMessages, messageNames, file.Proto.GetName())
	if err != nil {
		return fmt.Errorf("parsing sidecar %s: %w", sidecarPath, err)
	}
	if len(content.blocks) == 0 {
		return nil
	}

	outName := file.GeneratedFilenamePrefix + "_ext.pb.go"
	g := gen.NewGeneratedFile(outName, file.GoImportPath)
	writeExtFile(g.P, sidecarName, string(file.GoPackageName), content)

	return nil
}

// writeExtFile emits the generated extension file through the given
// line printer. Shared by the protoc-plugin and standalone paths.
func writeExtFile(p func(...interface{}), sidecarName, goPackage string, content *sidecarContent) {
	p("// Code generated by protoc-gen-extend. DO NOT EDIT.")
	p("// Source sidecar: ", sidecarName)
	p()
	p("package ", goPackage)
	p()

	if len(content.imports) > 0 {
		p("import (")
		for _, imp := range content.imports {
			p("\t", imp)
		}
		p(")")
		p()
	}

	for _, m := range content.blocks {
		p(m)
		p()
	}
}

// findSidecar searches for the sidecar file relative to the proto file
// location. It checks the current working directory combined with the proto
// directory, as well as common proto path roots.
func findSidecar(protoDir, sidecarName, sidecarRoot string) (string, error) {
	var candidates []string

	// If a sidecar_root is specified, prioritize it.
	if sidecarRoot != "" {
		candidates = append(candidates,
			filepath.Join(sidecarRoot, protoDir, sidecarName),
			filepath.Join(sidecarRoot, sidecarName),
		)
	}

	candidates = append(candidates,
		filepath.Join(protoDir, sidecarName),
		sidecarName,
	)

	cwd, err := os.Getwd()
	if err == nil {
		candidates = append(candidates,
			filepath.Join(cwd, protoDir, sidecarName),
			filepath.Join(cwd, sidecarName),
		)
	}

	seen := make(map[string]bool)
	for _, c := range candidates {
		abs, err := filepath.Abs(c)
		if err != nil {
			continue
		}
		if seen[abs] {
			continue
		}
		seen[abs] = true

		if _, err := os.Stat(abs); err == nil {
			return abs, nil
		}
	}

	return "", nil
}

// addNestedMessages recursively adds nested message names to the set.
func addNestedMessages(known map[string]bool, msg *protogen.Message) {
	for _, nested := range msg.Messages {
		known[nested.GoIdent.GoName] = true
		addNestedMessages(known, nested)
	}
}
