package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateExtensions looks for sidecar .proto.ext.go files next to the proto file
// and emits them into the generated output with the correct package name.
func generateExtensions(gen *protogen.Plugin, file *protogen.File, sidecarRoot string) error {
	protoPath := file.Proto.GetName()
	protoDir := filepath.Dir(protoPath)

	// The sidecar file convention: <name>.proto.ext.go sits next to <name>.proto.
	baseName := strings.TrimSuffix(filepath.Base(protoPath), ".proto")
	sidecarName := baseName + ".proto.ext.go"

	// Search for the sidecar file. protoc doesn't give us the absolute path
	// to the proto file directly, so we search proto_path entries, the
	// sidecar_root option, and the current working directory.
	sidecarPath, err := findSidecar(protoDir, sidecarName, sidecarRoot)
	if err != nil {
		return err
	}
	if sidecarPath == "" {
		// No sidecar file found — nothing to do.
		return nil
	}

	blocks, imports, err := parseSidecar(sidecarPath, file)
	if err != nil {
		return fmt.Errorf("parsing sidecar %s: %w", sidecarPath, err)
	}
	if len(blocks) == 0 {
		return nil
	}

	outName := file.GeneratedFilenamePrefix + "_ext.pb.go"
	g := gen.NewGeneratedFile(outName, file.GoImportPath)

	g.P("// Code generated by protoc-gen-extend. DO NOT EDIT.")
	g.P("// Source sidecar: ", sidecarName)
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	if len(imports) > 0 {
		g.P("import (")
		for _, imp := range imports {
			g.P("\t", imp)
		}
		g.P(")")
		g.P()
	}

	for _, m := range blocks {
		g.P(m)
		g.P()
	}

	return nil
}

// findSidecar searches for the sidecar file relative to the proto file
// location. It checks the current working directory combined with the proto
// directory, as well as common proto path roots.
func findSidecar(protoDir, sidecarName, sidecarRoot string) (string, error) {
	var candidates []string

	// If a sidecar_root is specified, prioritize it.
	if sidecarRoot != "" {
		candidates = append(candidates,
			filepath.Join(sidecarRoot, protoDir, sidecarName),
			filepath.Join(sidecarRoot, sidecarName),
		)
	}

	candidates = append(candidates,
		filepath.Join(protoDir, sidecarName),
		sidecarName,
	)

	cwd, err := os.Getwd()
	if err == nil {
		candidates = append(candidates,
			filepath.Join(cwd, protoDir, sidecarName),
			filepath.Join(cwd, sidecarName),
		)
	}

	seen := make(map[string]bool)
	for _, c := range candidates {
		abs, err := filepath.Abs(c)
		if err != nil {
			continue
		}
		if seen[abs] {
			continue
		}
		seen[abs] = true

		if _, err := os.Stat(abs); err == nil {
			return abs, nil
		}
	}

	return "", nil
}

// parseSidecar parses the sidecar .proto.ext.go file, validates that receivers
// reference messages defined in the proto file, and returns the source blocks
// ready to emit.
func parseSidecar(path string, file *protogen.File) (blocks []string, imports []string, err error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, err
	}

	fset := token.NewFileSet()
	astFile, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		return nil, nil, fmt.Errorf("parse error: %w", err)
	}

	// Build a set of known message names from the proto file.
	knownMessages := make(map[string]bool)
	var messageNames []string
	for _, msg := range file.Messages {
		knownMessages[msg.GoIdent.GoName] = true
		messageNames = append(messageNames, msg.GoIdent.GoName)
		addNestedMessages(knownMessages, msg)
	}

	// Collect imports from the sidecar (excluding the package declaration).
	for _, imp := range astFile.Imports {
		imports = append(imports, strings.TrimSpace(string(src[imp.Pos()-1:imp.End()-1])))
	}

	// Extract declarations: functions, methods, constants, and variables.
	for _, decl := range astFile.Decls {
		// Handle const/var/type declarations.
		if genDecl, ok := decl.(*ast.GenDecl); ok {
			// Skip import declarations (handled above).
			if genDecl.Tok == token.IMPORT {
				continue
			}
			block := string(src[genDecl.Pos()-1 : genDecl.End()-1])
			blocks = append(blocks, block)
			continue
		}

		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if fn.Recv == nil {
			// Top-level function (no receiver) — include it as-is.
			block := string(src[fn.Pos()-1 : fn.End()-1])
			blocks = append(blocks, block)
			continue
		}

		// Validate the receiver type is a known proto message.
		recvType := receiverTypeName(fn.Recv)
		if recvType == "" {
			continue
		}
		if !knownMessages[recvType] {
			return nil, nil, fmt.Errorf(
				"method %s has receiver *%s, but %s is not a message in %s\n  available messages: %s",
				fn.Name.Name, recvType, recvType, file.Proto.GetName(),
				strings.Join(messageNames, ", "),
			)
		}

		block := string(src[fn.Pos()-1 : fn.End()-1])
		blocks = append(blocks, block)
	}

	return blocks, imports, nil
}

// receiverTypeName extracts the type name from a method receiver. It handles
// both pointer (*User) and value (User) receivers.
func receiverTypeName(fields *ast.FieldList) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	expr := fields.List[0].Type

	// Pointer receiver: *User
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}

	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name
	}
	return ""
}

// addNestedMessages recursively adds nested message names to the set.
func addNestedMessages(known map[string]bool, msg *protogen.Message) {
	for _, nested := range msg.Messages {
		known[nested.GoIdent.GoName] = true
		addNestedMessages(known, nested)
	}
}
