package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const standaloneProto = `
syntax = "proto3";
package test;
option go_package = "example.com/mod/gen/testpb";

message User {
  string first_name = 1;
  message Settings {
    bool dark_mode = 1;
  }
}
`

const standaloneSidecar = `//go:build ignore

package testpb

import "strings"

// FullName returns the trimmed first name.
func (u *User) FullName() string {
	return strings.TrimSpace(u.FirstName)
}

// IsDark reports dark mode.
func (s *User_Settings) IsDark() bool {
	return s.DarkMode
}
`

func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, content := range files {
		p := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func TestStandaloneModuleMode(t *testing.T) {
	t.Parallel()
	root := writeTree(t, map[string]string{
		"protos/user/user.proto":        standaloneProto,
		"protos/user/user.proto.ext.go": standaloneSidecar,
	})
	out := filepath.Join(root, "out")

	err := runGenerate([]string{
		"-sidecar_root", filepath.Join(root, "protos"),
		"-out", out,
		"-module", "example.com/mod",
	})
	if err != nil {
		t.Fatal(err)
	}

	// module mode: go_package minus module prefix -> out/gen/testpb/
	got, err := os.ReadFile(filepath.Join(out, "gen", "testpb", "user_ext.pb.go"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"package testpb",
		"// FullName returns the trimmed first name.",
		"func (u *User) FullName() string",
		"func (s *User_Settings) IsDark() bool",
		`"strings"`,
		"// Code generated by protoc-gen-extend. DO NOT EDIT.",
	} {
		if !strings.Contains(string(got), want) {
			t.Errorf("output missing %q\n---\n%s", want, got)
		}
	}
}

func TestStandaloneSourceRelative(t *testing.T) {
	t.Parallel()
	root := writeTree(t, map[string]string{
		"protos/user/user.proto":        standaloneProto,
		"protos/user/user.proto.ext.go": standaloneSidecar,
	})
	out := filepath.Join(root, "out")

	err := runGenerate([]string{
		"-sidecar_root", filepath.Join(root, "protos"),
		"-out", out,
		"-paths_source_relative",
	})
	if err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Join(out, "user", "user_ext.pb.go")); err != nil {
		t.Fatalf("source_relative output missing: %v", err)
	}
}

func TestStandaloneUnknownReceiver(t *testing.T) {
	t.Parallel()
	root := writeTree(t, map[string]string{
		"user.proto": standaloneProto,
		"user.proto.ext.go": `//go:build ignore

package testpb

func (x *Nope) Bad() {}
`,
	})

	err := runGenerate([]string{
		"-sidecar_root", root,
		"-out", filepath.Join(root, "out"),
		"-paths_source_relative",
	})
	if err == nil || !strings.Contains(err.Error(), "Nope is not a message") {
		t.Fatalf("expected unknown-receiver error, got %v", err)
	}
	if err != nil && !strings.Contains(err.Error(), "User") {
		t.Errorf("error should list available messages, got %v", err)
	}
}

func TestStandaloneMissingProto(t *testing.T) {
	t.Parallel()
	root := writeTree(t, map[string]string{
		"orphan.proto.ext.go": standaloneSidecar,
	})

	err := runGenerate([]string{
		"-sidecar_root", root,
		"-out", filepath.Join(root, "out"),
		"-paths_source_relative",
	})
	if err == nil || !strings.Contains(err.Error(), "no matching proto") {
		t.Fatalf("expected missing-proto error, got %v", err)
	}
}

func TestStandaloneFlagValidation(t *testing.T) {
	t.Parallel()
	if err := runGenerate([]string{"-out", "x"}); err == nil {
		t.Error("expected error when neither -module nor -paths_source_relative given")
	}
	if err := runGenerate([]string{"-out", "x", "-module", "m", "-paths_source_relative"}); err == nil {
		t.Error("expected error when both -module and -paths_source_relative given")
	}
	if err := runGenerate([]string{"-module", "m"}); err == nil {
		t.Error("expected error when -out missing")
	}
}

func TestStandaloneNoSidecarsIsNoop(t *testing.T) {
	t.Parallel()
	root := writeTree(t, map[string]string{
		"plain.proto": standaloneProto,
	})
	if err := runGenerate([]string{"-sidecar_root", root, "-out", filepath.Join(root, "out"), "-module", "example.com/mod"}); err != nil {
		t.Fatalf("no-sidecar tree should be a no-op, got %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "out")); !os.IsNotExist(err) {
		t.Error("out dir should not be created when nothing is generated")
	}
}

func TestStandaloneTestSidecar(t *testing.T) {
	t.Parallel()
	root := writeTree(t, map[string]string{
		"protos/user/user.proto":        standaloneProto,
		"protos/user/user.proto.ext.go": standaloneSidecar,
		"protos/user/user.proto.ext_test.go": `//go:build ignore

package testpb

import "testing"

// TestFullName exercises the generated extension method.
func TestFullName(t *testing.T) {
	u := &User{FirstName: " a "}
	if u.FullName() != "a" {
		t.Fatal("trim failed")
	}
}
`,
	})
	out := filepath.Join(root, "out")

	if err := runGenerate([]string{
		"-sidecar_root", filepath.Join(root, "protos"),
		"-out", out,
		"-module", "example.com/mod",
	}); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(out, "gen", "testpb", "user_ext.pb_test.go"))
	if err != nil {
		t.Fatalf("test sidecar output missing: %v", err)
	}
	for _, want := range []string{
		"package testpb",
		"func TestFullName(t *testing.T)",
		"// TestFullName exercises the generated extension method.",
		`"testing"`,
	} {
		if !strings.Contains(string(got), want) {
			t.Errorf("test output missing %q\n---\n%s", want, got)
		}
	}

	// The production output must not absorb the test content.
	prod, err := os.ReadFile(filepath.Join(out, "gen", "testpb", "user_ext.pb.go"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(prod), "testing") {
		t.Error("production ext file must not import testing")
	}
}
